### ISSUE TITLE
Driver [qq] not supported.

### ISSUE THREAD

**Issue by ivanzhang** [SocialiteProviders/QQ#2]
this error occurs on laravel 5.1

**Comment by DraperStudio** [comment]
Works without any issues if you do everything like it is instructed in the documentation.

**Comment by liyu001989** [comment]
must add this in  app/Providers/EventServiceProvider.php

'SocialiteProviders\Manager\SocialiteWasCalled' => [
    'SocialiteProviders\Qq\QqExtendSocialite'
]

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/socialiteproviders.github.io/commit/453369c1bf1c04c20978ed1119acacebeb3921d6
