### ISSUE TITLE
document error

### ISSUE THREAD

**Issue by jhdxr** [SocialiteProviders/QQ#3]
http://socialiteproviders.github.io/providers/qq/ says
> The listener that you add for this provider is 'SocialiteProviders\QQ\QqExtendSocialite@handle',.
which should be `SocialiteProviders\Qq\QqExtendSocialite@handle`.

and I think it's the reason of #2  ，because it faild to register handler, then no driver named qq can be called.

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/socialiteproviders.github.io/commit/453369c1bf1c04c20978ed1119acacebeb3921d6
