### ISSUE TITLE
FatalErrorException in RouteServiceProvider.php line 33:

### ISSUE THREAD

**Issue by ailias** [SocialiteProviders/QQ#5]
Hello,I am stuck in the error about "Call to undefined method Illuminate\Routing\RouteCollection::refreshNameLookups()" when I followed by the step of the method in this url:"http://socialiteproviders.github.io/providers/qq/ " .It said that it cannot find the refreshNameLookups function but I saw it in RouteCollection class.
Unfortunatly there is few information about  the error, so what should I deal with the problems?
![Uploading QQ拼音截图未命名.png…]()

**Comment by ailias** [comment]
![qq](https://cloud.githubusercontent.com/assets/10510469/10909957/638023b8-8277-11e5-80e8-c79adadfca55.png)

**Comment by brnlbs** [comment]
That doesn't seem to be related to our Provider or Socialite.
