### ISSUE TITLE
[Symfony\Component\Debug\Exception\FatalErrorException]                  Class 'SocialiteProviders\Manager\OAuth2\AbstractProvider' not found

### ISSUE THREAD

**Issue by awh521** [SocialiteProviders/QQ#6]
[Symfony\Component\Debug\Exception\FatalErrorException]               
  Class 'SocialiteProviders\Manager\OAuth2\AbstractProvider' not found
what's wrong,how can I fix this problem? 3q

**Comment by DraperStudio** [comment]
Which version of the QQ Provider are you using?

**Comment by awh521** [comment]
I'm sorry.I don't add "socialiteproviders/manager": "^2.0" to my composer.json.Now the problem is solved.But I have another problem:Driver [weibo] not supported.I'm confused.

**Comment by AndyWendt** [comment]
https://www.youtube.com/watch?v=Vhh_GeBPOhs

**Comment by awh521** [comment]
Solved.
