### ISSUE TITLE
login by qq error

### ISSUE THREAD

**Issue by bfsong** [SocialiteProviders/QQ#8]
Provider.php line 104:
`$this->credentialsResponseBody = $body;`

$this->credentialsResponseBody  need a array, but $body is a string, 
it cause error in  SocialiteProviders\Manager\OAuth2\AbstractProvider.php 

i add a function in Provider.php
public function convertToArray($value){
        $s = explode('&', $value);
        $a = [];
        foreach($s as $item){
            $s2 = explode('=', $item);
            $a[$s2[0]] = $s2[1];
        }
        return $a;
    }

than change line 104 to:
`$this->credentialsResponseBody = $this->convertToArray($body);`

**Comment by DraperStudio** [comment]
Can you provide test credentials **(client id, client secret)** so that I can try to fix the issue?

**Comment by DraperStudio** [comment]
@bfsong I have made a change which should fix this, try `composer update` and see if it works with the new version.
