### ISSUE TITLE
login by qq error：Undefined index: openid

### ISSUE THREAD

**Issue by falstack** [SocialiteProviders/QQ#9]
ErrorException in Provider.php line 57:
Undefined index: openid

**Comment by DraperStudio** [comment]
If no `openid` is defined you probably have the wrong scopes or something went wrong while performing the login.

Can't do much without more details and a dump of your response.

**Comment by awh521** [comment]
`
//vendor/socialiteproviders/qq/src/Provider.php
// I don't want to edit the original source,but it's wrong.
public function getAccessToken($code)
    {
        $response = $this->getHttpClient()->get($this->getTokenUrl(), [
            'query' => $this->getTokenFields($code),
        ]);
        $token=$response->getBody()->getContents(); 
        $this->credentialsResponseBody = (array)json_decode($response->getBody(), true);
        return $token;
    }`

**Comment by DraperStudio** [comment]
Should be fixed by https://github.com/SocialiteProviders/QQ/pull/10/commits/734526d63e9d3e2b8773867aa14b39df275af0bf

**Comment by DraperStudio** [comment]
Closed for now, send a PR with a fix if the issue still occurs.
